name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-22.04
  #   steps:
  # - uses: actions/download-artifact@v4
  #   with:
  #     name: public
  #     path: public
